<!DOCTYPE HTML>
<html>
<head>
<title>OnError</title>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="robots" content="noindex, nofollow">
<link href="../static/theme.css" rel="stylesheet" type="text/css" />
<script src="../static/content.js" type="text/javascript"></script>
<script src="../static/ga.js" type="text/javascript"></script>
</head>
<body>

<h1>OnError</h1>
<p>Bestimmt eine <a href="../Functions.htm">Funktion</a>, die automatisch gestartet werden soll, wenn ein unbehandelter Fehler auftritt.</p>

<pre class="Syntax"><span class="func">OnError</span> Func <span class="optional">, AddRemove</span></pre>

<h3>Parameter</h3>
<dl>

  <dt>Func</dt>
  <dd><p>Ein Funktionsname oder <a href="../objects/Functor.htm">Funktionsobjekt</a>, die aufgerufen werden sollen, wenn ein unbehandelter Fehler auftritt. Die Funktion erhält das Exception-Objekt als Parameter. Sie kann via Return einen Integer ungleich Null zurückgeben, um die Standardfehlermeldung zu unterdrücken.</p></dd>
  
  <dt>HinzufügenEntfernen</dt>
  <dd><p>Eines der folgenden Werte:<br>
  <strong>1</strong> (Standard): Rufen Sie die Funktion nach anderen zuvor registrierten Funktionen auf.<br>
  <strong>-1</strong>: Rufen Sie die Funktion vor anderen zuvor registrierten Funktionen auf.<br>
  <strong>0</strong>: Rufen Sie die Funktion nicht auf.</p>
  </dd>

</dl>

<h3>Bemerkungen</h3>
<p><em>Func</em> wird nur bei Fehlern oder Ausnahmen aufgerufen, die normalerweise zu einer Fehlermeldung führen würden. Ladezeitfehler gehören nicht dazu, da OnError erst nach dem Laden des Skripts aufgerufen werden kann.</p>
<p>Wenn eine Fehlerfunktion einen Integer ungleich Null via Return zurückgibt, wird der Thread beendet. Wenn innerhalb einer Fehlerfunktion ein Fehler auftritt (oder eine Ausnahme ausgelöst wird), wird eine Fehlermeldung für den neuen Fehler angezeigt und der Thread beendet. Ansonsten werden alle Fehlerfunktionen aufgerufen, eine Fehlermeldung angezeigt und der Thread beendet.</p>
<p><em>Func</em>'s erster Parameter erhält den Wert oder das <a href="Throw.htm#Exception">Exception</a>-Objekt der ausgelösten Ausnahme. Wenn es sich um ein Objekt handelt, kann es modifiziert werden, um zu bestimmen, was die Standardfehlermeldung anzeigen soll.</p>
<p><em>Func</em> wird während des aktuellen <a href="../misc/Threads.htm">Threads</a> aufgerufen, bevor er beendet wird (also bevor der Aufrufstapel abgearbeitet wurde).</p>

<h3>Siehe auch</h3>
<p><a href="Try.htm">Try</a>, <a href="Catch.htm">Catch</a>, <a href="Throw.htm">Throw</a>, <a href="OnExit.htm">OnExit</a></p>

<h3 id="Examples">Beispiele</h3>
<pre class="NoIndent">
OnError "FehlerProtokollieren"
%Fehler% := auslösen

FehlerProtokollieren(Exception) {
    FileAppend "Fehler bei Zeile " Exception.Line ": " Exception.Message "`n"
        , "Fehlerprotokoll.txt"
    return true
}
</pre>

</body>
</html>
